namespace DbNetSuiteCore.Enums
{
    public enum ColumnPropertyType
    {
        Aggregate,
        ClearDuplicateValue,
        DataType,
        DataOnly,
        Display,
        Download,
        Filter,
        FilterMode,
        ForeignKey,
        Format,
        GroupHeader,
        Image,
        Label,
        Lookup,
        PrimaryKey,
        Search,
        Style,
        TotalBreak,
        View,
        Extension,
        UploadMetaData,
        UploadMetaDataColumn,
        ColumnSize,
        EditControlType,
        Pattern,
        ReadOnly,
        Required,
        Browse
    }
}
