//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbNetSuiteCore.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _default {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _default() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbNetSuiteCore.Resources.Localization.default", typeof(_default).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new record.
        /// </summary>
        internal static string AddANewRecord {
            get {
                return ResourceManager.GetString("AddANewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new set of search criteria.
        /// </summary>
        internal static string AddNewSearch {
            get {
                return ResourceManager.GetString("AddNewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        internal static string AdvancedSearch {
            get {
                return ResourceManager.GetString("AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        internal static string After {
            get {
                return ResourceManager.GetString("After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rows.
        /// </summary>
        internal static string AllRows {
            get {
                return ResourceManager.GetString("AllRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply changes to the current record.
        /// </summary>
        internal static string ApplyChangesToTheCurrentRecord {
            get {
                return ResourceManager.GetString("ApplyChangesToTheCurrentRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply the entered search criteria.
        /// </summary>
        internal static string ApplyTheEnteredSearchCriteria {
            get {
                return ResourceManager.GetString("ApplyTheEnteredSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A row must be selected.
        /// </summary>
        internal static string ARowMustBeSelected {
            get {
                return ResourceManager.GetString("ARowMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value is required for.
        /// </summary>
        internal static string AValueIsRequiredFor {
            get {
                return ResourceManager.GetString("AValueIsRequiredFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        internal static string Before {
            get {
                return ResourceManager.GetString("Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between.
        /// </summary>
        internal static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Configuration.
        /// </summary>
        internal static string ChartConfig {
            get {
                return ResourceManager.GetString("ChartConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the chart configuration dialog.
        /// </summary>
        internal static string ChartGrid {
            get {
                return ResourceManager.GetString("ChartGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check spelling.
        /// </summary>
        internal static string CheckSpelling {
            get {
                return ResourceManager.GetString("CheckSpelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the search criteria.
        /// </summary>
        internal static string ClearTheSearchCriteria {
            get {
                return ResourceManager.GetString("ClearTheSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the search window.
        /// </summary>
        internal static string CloseTheSearchWindow {
            get {
                return ResourceManager.GetString("CloseTheSearchWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Selection.
        /// </summary>
        internal static string ColumnPicker {
            get {
                return ResourceManager.GetString("ColumnPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Sort Selection Dialog.
        /// </summary>
        internal static string ColumnSort {
            get {
                return ResourceManager.GetString("ColumnSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime Configuration Dialog.
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected record(s) ?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy page to clipboard.
        /// </summary>
        internal static string Copy_Title {
            get {
                return ResourceManager.GetString("Copy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy grid to clipboard.
        /// </summary>
        internal static string CopyGridToClipboard {
            get {
                return ResourceManager.GetString("CopyGridToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy To Clipboard.
        /// </summary>
        internal static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new folder.
        /// </summary>
        internal static string CreateFolder {
            get {
                return ResourceManager.GetString("CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Save.
        /// </summary>
        internal static string CustomSave {
            get {
                return ResourceManager.GetString("CustomSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value entered into &lt;b&gt;{0}&lt;/b&gt; is not valid for data type.
        /// </summary>
        internal static string DataMismatch {
            get {
                return ResourceManager.GetString("DataMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Upload Column Mapping.
        /// </summary>
        internal static string DataUploadDialog {
            get {
                return ResourceManager.GetString("DataUploadDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date value is not valid.
        /// </summary>
        internal static string DateNotValid {
            get {
                return ResourceManager.GetString("DateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting of records is not enabled for for this control.
        /// </summary>
        internal static string DeleteDisabled {
            get {
                return ResourceManager.GetString("DeleteDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete document.
        /// </summary>
        internal static string DeleteDocument {
            get {
                return ResourceManager.GetString("DeleteDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the currently selected file.
        /// </summary>
        internal static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm you wish to delete the selected file.
        /// </summary>
        internal static string DeleteFileConfirm {
            get {
                return ResourceManager.GetString("DeleteFileConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm you wish to delete the selected folder and all of its contents.
        /// </summary>
        internal static string DeleteFolderConfirm {
            get {
                return ResourceManager.GetString("DeleteFolderConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Deleterow {
            get {
                return ResourceManager.GetString("Deleterow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the current record.
        /// </summary>
        internal static string DeleteTheCurrentRecord {
            get {
                return ResourceManager.GetString("DeleteTheCurrentRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected record.
        /// </summary>
        internal static string DeleteTheSelectedRecord {
            get {
                return ResourceManager.GetString("DeleteTheSelectedRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the search window.
        /// </summary>
        internal static string DisplayTheSearchWindow {
            get {
                return ResourceManager.GetString("DisplayTheSearchWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document copied to clipboard.
        /// </summary>
        internal static string DocumentCopied {
            get {
                return ResourceManager.GetString("DocumentCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy not supported for this document type.
        /// </summary>
        internal static string DocumentNotCopied {
            get {
                return ResourceManager.GetString("DocumentNotCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not contain.
        /// </summary>
        internal static string DoesNotContain {
            get {
                return ResourceManager.GetString("DoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not end with.
        /// </summary>
        internal static string DoesNotEndWith {
            get {
                return ResourceManager.GetString("DoesNotEndWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not start with.
        /// </summary>
        internal static string DoesNotStartWith {
            get {
                return ResourceManager.GetString("DoesNotStartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data in selected format.
        /// </summary>
        internal static string Download_Title {
            get {
                return ResourceManager.GetString("Download_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag your file here.
        /// </summary>
        internal static string DragYourFileHere {
            get {
                return ResourceManager.GetString("DragYourFileHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with the same name already exists.  Please select another name..
        /// </summary>
        internal static string DuplicateFileName {
            get {
                return ResourceManager.GetString("DuplicateFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditDialogTitle {
            get {
                return ResourceManager.GetString("EditDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        internal static string EndsWith {
            get {
                return ResourceManager.GetString("EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal to.
        /// </summary>
        internal static string EqualTo {
            get {
                return ResourceManager.GetString("EqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured.
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered value should be in the following format.
        /// </summary>
        internal static string ExampleFormat {
            get {
                return ResourceManager.GetString("ExampleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing file extensions is not permitted.  Please ensure the new extension matches the old one..
        /// </summary>
        internal static string ExtensionChangeWarning {
            get {
                return ResourceManager.GetString("ExtensionChangeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed custom validation.
        /// </summary>
        internal static string FailedCustomValidation {
            get {
                return ResourceManager.GetString("FailedCustomValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the file has been denied.
        /// </summary>
        internal static string FileAccessDenied {
            get {
                return ResourceManager.GetString("FileAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Attributes.
        /// </summary>
        internal static string FileAttributes {
            get {
                return ResourceManager.GetString("FileAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Content.
        /// </summary>
        internal static string FileContent {
            get {
                return ResourceManager.GetString("FileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Deletion Has Been Denied.
        /// </summary>
        internal static string FileDeletionDenied {
            get {
                return ResourceManager.GetString("FileDeletionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file exceeds the maximum permitted file size.  Please upload a file smaller than {0}Kb.
        /// </summary>
        internal static string FileExceedsMaxSize {
            get {
                return ResourceManager.GetString("FileExceedsMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with this name already exists..
        /// </summary>
        internal static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Preview.
        /// </summary>
        internal static string FilePreview {
            get {
                return ResourceManager.GetString("FilePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Search.
        /// </summary>
        internal static string FileSearch {
            get {
                return ResourceManager.GetString("FileSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Search Results.
        /// </summary>
        internal static string FileSearchResults {
            get {
                return ResourceManager.GetString("FileSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Upload.
        /// </summary>
        internal static string FileUpload {
            get {
                return ResourceManager.GetString("FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded.
        /// </summary>
        internal static string FileUploaded {
            get {
                return ResourceManager.GetString("FileUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to first page.
        /// </summary>
        internal static string First_Title {
            get {
                return ResourceManager.GetString("First_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First page.
        /// </summary>
        internal static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Row.
        /// </summary>
        internal static string FirstRow {
            get {
                return ResourceManager.GetString("FirstRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Name.
        /// </summary>
        internal static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder is not empty.
        /// </summary>
        internal static string FolderNotEmpty {
            get {
                return ResourceManager.GetString("FolderNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Family.
        /// </summary>
        internal static string FontFamily {
            get {
                return ResourceManager.GetString("FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than.
        /// </summary>
        internal static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The grid has been copied to the clipboard.
        /// </summary>
        internal static string GridCopied {
            get {
                return ResourceManager.GetString("GridCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format of highlighted values is not correct.
        /// </summary>
        internal static string HighlightedFormatInvalid {
            get {
                return ResourceManager.GetString("HighlightedFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Editor.
        /// </summary>
        internal static string HTMLEditor {
            get {
                return ResourceManager.GetString("HTMLEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include sub-folders.
        /// </summary>
        internal static string Includesub_folders {
            get {
                return ResourceManager.GetString("Includesub-folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserting of records is not enabled for for this control.
        /// </summary>
        internal static string InsertDisabled {
            get {
                return ResourceManager.GetString("InsertDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Insertrow {
            get {
                return ResourceManager.GetString("Insertrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer value is not valid.
        /// </summary>
        internal static string IntegerNotValid {
            get {
                return ResourceManager.GetString("IntegerNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered email address is not valid.
        /// </summary>
        internal static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot upload a file of this type.
        /// </summary>
        internal static string InvalidFileType {
            get {
                return ResourceManager.GetString("InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid range.
        /// </summary>
        internal static string InvalidRange {
            get {
                return ResourceManager.GetString("InvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not null.
        /// </summary>
        internal static string IsNotNull {
            get {
                return ResourceManager.GetString("IsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is null.
        /// </summary>
        internal static string IsNull {
            get {
                return ResourceManager.GetString("IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilobytes.
        /// </summary>
        internal static string KB {
            get {
                return ResourceManager.GetString("KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to last page.
        /// </summary>
        internal static string Last_Title {
            get {
                return ResourceManager.GetString("Last_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        internal static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last page.
        /// </summary>
        internal static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Row.
        /// </summary>
        internal static string LastRow {
            get {
                return ResourceManager.GetString("LastRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than.
        /// </summary>
        internal static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected record cannot be deleted because because it has related records.
        /// </summary>
        internal static string LinkedRecords {
            get {
                return ResourceManager.GetString("LinkedRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup.
        /// </summary>
        internal static string Lookup {
            get {
                return ResourceManager.GetString("Lookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match all of the criteria.
        /// </summary>
        internal static string MatchAllCriteria {
            get {
                return ResourceManager.GetString("MatchAllCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match at least one of the criteria.
        /// </summary>
        internal static string MatchAtLeastOneCriteria {
            get {
                return ResourceManager.GetString("MatchAtLeastOneCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megabytes.
        /// </summary>
        internal static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge selected records with a Word merge document.
        /// </summary>
        internal static string MergeData {
            get {
                return ResourceManager.GetString("MergeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        internal static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to next page.
        /// </summary>
        internal static string Next_Title {
            get {
                return ResourceManager.GetString("Next_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next month.
        /// </summary>
        internal static string NextMonth {
            get {
                return ResourceManager.GetString("NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        internal static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next record.
        /// </summary>
        internal static string NextRecord_Title {
            get {
                return ResourceManager.GetString("NextRecord_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Row.
        /// </summary>
        internal static string NextRow {
            get {
                return ResourceManager.GetString("NextRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found.
        /// </summary>
        internal static string No_Records_Found {
            get {
                return ResourceManager.GetString("No_Records_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file or folder has been selected.
        /// </summary>
        internal static string NoFileSelected {
            get {
                return ResourceManager.GetString("NoFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Paging.
        /// </summary>
        internal static string NoPaging {
            get {
                return ResourceManager.GetString("NoPaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found.
        /// </summary>
        internal static string NoRecordsFound {
            get {
                return ResourceManager.GetString("NoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not between.
        /// </summary>
        internal static string NotBetween {
            get {
                return ResourceManager.GetString("NotBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not equal to.
        /// </summary>
        internal static string NotEqualTo {
            get {
                return ResourceManager.GetString("NotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not greater than.
        /// </summary>
        internal static string NotGreaterThan {
            get {
                return ResourceManager.GetString("NotGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not in.
        /// </summary>
        internal static string NotIn {
            get {
                return ResourceManager.GetString("NotIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not less than.
        /// </summary>
        internal static string NotLessThan {
            get {
                return ResourceManager.GetString("NotLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of.
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open browse dialog.
        /// </summary>
        internal static string OpenBrowseDialog {
            get {
                return ResourceManager.GetString("OpenBrowseDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the column selection dialog.
        /// </summary>
        internal static string OpenColumnSelectionDialog {
            get {
                return ResourceManager.GetString("OpenColumnSelectionDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the column sort dialog.
        /// </summary>
        internal static string OpenColumnSortDialog {
            get {
                return ResourceManager.GetString("OpenColumnSortDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open runtime configuration dialog.
        /// </summary>
        internal static string OpenConfigDialog {
            get {
                return ResourceManager.GetString("OpenConfigDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the editor window.
        /// </summary>
        internal static string OpenEditorWindow {
            get {
                return ResourceManager.GetString("OpenEditorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open In New Window.
        /// </summary>
        internal static string OpenInNewWindow {
            get {
                return ResourceManager.GetString("OpenInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the lookup window.
        /// </summary>
        internal static string OpenTheLookupWindow {
            get {
                return ResourceManager.GetString("OpenTheLookupWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open User Profile dialog.
        /// </summary>
        internal static string OpenUserProfileDialog {
            get {
                return ResourceManager.GetString("OpenUserProfileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output current page only.
        /// </summary>
        internal static string OutputCurrentPageOnly {
            get {
                return ResourceManager.GetString("OutputCurrentPageOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output page size.
        /// </summary>
        internal static string OutputPageSize {
            get {
                return ResourceManager.GetString("OutputPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with this name already exists.  Would you like to overwrite it?.
        /// </summary>
        internal static string OverwritePrompt {
            get {
                return ResourceManager.GetString("OverwritePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display page size.
        /// </summary>
        internal static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Settings.
        /// </summary>
        internal static string PdfSettings {
            get {
                return ResourceManager.GetString("PdfSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        internal static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to previous page.
        /// </summary>
        internal static string Previous_Title {
            get {
                return ResourceManager.GetString("Previous_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous month.
        /// </summary>
        internal static string PreviousMonth {
            get {
                return ResourceManager.GetString("PreviousMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        internal static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous record.
        /// </summary>
        internal static string PreviousRecord_Title {
            get {
                return ResourceManager.GetString("PreviousRecord_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Row.
        /// </summary>
        internal static string PreviousRow {
            get {
                return ResourceManager.GetString("PreviousRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print grid.
        /// </summary>
        internal static string PrintGrid {
            get {
                return ResourceManager.GetString("PrintGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print the current record.
        /// </summary>
        internal static string PrintTheCurrentRecord {
            get {
                return ResourceManager.GetString("PrintTheCurrentRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search records.
        /// </summary>
        internal static string QuickSearch_Title {
            get {
                return ResourceManager.GetString("QuickSearch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        internal static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted.
        /// </summary>
        internal static string RecordDeleted {
            get {
                return ResourceManager.GetString("RecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record inserted.
        /// </summary>
        internal static string RecordInserted {
            get {
                return ResourceManager.GetString("RecordInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records deleted.
        /// </summary>
        internal static string RecordsDeleted {
            get {
                return ResourceManager.GetString("RecordsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record updated.
        /// </summary>
        internal static string RecordUpdated {
            get {
                return ResourceManager.GetString("RecordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename File:.
        /// </summary>
        internal static string RenameFile {
            get {
                return ResourceManager.GetString("RenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        internal static string Rows {
            get {
                return ResourceManager.GetString("Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Profile.
        /// </summary>
        internal static string SaveProfile {
            get {
                return ResourceManager.GetString("SaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the grid in the selected format.
        /// </summary>
        internal static string SaveTheGridInTheSelectedFormat {
            get {
                return ResourceManager.GetString("SaveTheGridInTheSelectedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search files only.
        /// </summary>
        internal static string Searchfilesonly {
            get {
                return ResourceManager.GetString("Searchfilesonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file to upload..
        /// </summary>
        internal static string SelectAFile {
            get {
                return ResourceManager.GetString("SelectAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select date.
        /// </summary>
        internal static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Profile.
        /// </summary>
        internal static string SelectProfile {
            get {
                return ResourceManager.GetString("SelectProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select time.
        /// </summary>
        internal static string SelectTime {
            get {
                return ResourceManager.GetString("SelectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select value.
        /// </summary>
        internal static string SelectValue {
            get {
                return ResourceManager.GetString("SelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show calendar.
        /// </summary>
        internal static string ShowCalendar {
            get {
                return ResourceManager.GetString("ShowCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        internal static string Simple {
            get {
                return ResourceManager.GetString("Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Search.
        /// </summary>
        internal static string SimpleSearch {
            get {
                return ResourceManager.GetString("SimpleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spelling Checker.
        /// </summary>
        internal static string SpellCheck {
            get {
                return ResourceManager.GetString("SpellCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Search.
        /// </summary>
        internal static string StandardSearch {
            get {
                return ResourceManager.GetString("StandardSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with.
        /// </summary>
        internal static string StartsWith {
            get {
                return ResourceManager.GetString("StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to advanced editing.
        /// </summary>
        internal static string SwitchToAdvancedEditing {
            get {
                return ResourceManager.GetString("SwitchToAdvancedEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to simple editing.
        /// </summary>
        internal static string SwitchToSimpleEditing {
            get {
                return ResourceManager.GetString("SwitchToSimpleEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Editor.
        /// </summary>
        internal static string TextEditor {
            get {
                return ResourceManager.GetString("TextEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unapplied changes. Discard ?.
        /// </summary>
        internal static string UnappliedChanges {
            get {
                return ResourceManager.GetString("UnappliedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Updaterow {
            get {
                return ResourceManager.GetString("Updaterow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating of records is not enabled for for this control.
        /// </summary>
        internal static string UpdatesDisabled {
            get {
                return ResourceManager.GetString("UpdatesDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the selected record.
        /// </summary>
        internal static string UpdateTheSelectedRecord {
            get {
                return ResourceManager.GetString("UpdateTheSelectedRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload .
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a file to the current folder.
        /// </summary>
        internal static string UploadAFile {
            get {
                return ResourceManager.GetString("UploadAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload complete.
        /// </summary>
        internal static string UploadComplete {
            get {
                return ResourceManager.GetString("UploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload data.
        /// </summary>
        internal static string UploadData {
            get {
                return ResourceManager.GetString("UploadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload document.
        /// </summary>
        internal static string UploadDocument {
            get {
                return ResourceManager.GetString("UploadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profiles.
        /// </summary>
        internal static string UserProfiles {
            get {
                return ResourceManager.GetString("UserProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value is required in this field.
        /// </summary>
        internal static string ValueRequired {
            get {
                return ResourceManager.GetString("ValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the selected record.
        /// </summary>
        internal static string View_Title {
            get {
                return ResourceManager.GetString("View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Dialog.
        /// </summary>
        internal static string ViewDialogTitle {
            get {
                return ResourceManager.GetString("ViewDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the selected record.
        /// </summary>
        internal static string ViewTheSelectedRecord {
            get {
                return ResourceManager.GetString("ViewTheSelectedRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
